name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/checkout-submodules
      with:
        fetch-depth: 0
        submodules: false
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
