name: CI

on:
  push:
    branches: [ main, win ]
  pull_request:
    branches: [ main, win ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build_and_test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
